### ISSUE TITLE
custom-dataset onnx

### ISSUE THREAD

**Issue by Yakiw** [Hyuto/yolo-nas-onnx#1] opened 2023-05-30 05:52 UTC
when i use default coco dataset and convert it into ONNX, after inference i will get true detect result
but when i use custom dataset  , convert   yolo-nas train weight "pth"  into ONNX, after inference i can't get  true detect result
so  have u tried custom dataset ONNX on your code  and the results?
thanks for answering!!!

**Comment by Uaena-Wang** [comment] 2023-05-30 07:17
thank u！ i have tried it but no effect ,  i think my problem is my "ONNX" itself, but i dont know how to solve it, can i trouble you email  u?

**Comment by Hyuto** [comment] 2023-05-30 07:25
Sure, you can reach me on wahyusetianto19@gmail.com. 

Please attach your onnx model with the labels so I can test it.

**Comment by xinsuinizhuan** [comment] 2023-05-31 03:38
how you convert the .pth to onnx？could share you convert .py file? could you simplify it?

**Comment by xinsuinizhuan** [comment] 2023-05-31 03:49
or could you share you converted onnx models? I trtexe my onnx to trt, but the parseFromFile could not parase the onnx

**Comment by Uaena-Wang** [comment] 2023-05-31 04:42
I use super_gradients script

from super_gradients.training import models
net = models.get('yolo_nas_s', num_classes= 6, checkpoint_path='/home/featurize/data/YOLO-NAS/runs/train0/ckpt_best.pth')
models.convert_to_onnx(model=net, input_shape=(3, 320, 320), out_path='yolo-nas-s.onnx')

after run above code , U will get onnx model, that is converting .pth to onnx
becausu onnx model is a bit big , U can reach me on marquitaschramekzmx27@gmail.com , I will share my onnx and .pth file with U!

**Comment by Uaena-Wang** [comment] 2023-05-31 04:42
> or could you share you converted onnx models? I trtexe my onnx to trt, but the parseFromFile could not parase the onnx

I use super_gradients script

from super_gradients.training import models
net = models.get('yolo_nas_s', num_classes= 6, checkpoint_path='/home/featurize/data/YOLO-NAS/runs/train0/ckpt_best.pth')
models.convert_to_onnx(model=net, input_shape=(3, 320, 320), out_path='yolo-nas-s.onnx')

after run above code , U will get onnx model, that is converting .pth to onnx
becausu onnx model is a bit big , U can reach me on [marquitaschramekzmx27@gmail.com](mailto:marquitaschramekzmx27@gmail.com) , I will share my onnx and .pth file with U!

**Comment by xinsuinizhuan** [comment] 2023-05-31 07:03
I use the code to export, error:
from super_gradients.training import models
net = models.get('yolo_nas_s', num_classes= 80, checkpoint_path='yolo_nas_s_coco.pth')
models.convert_to_onnx(model=net, input_shape=(3, 640, 640), out_path='yolo-nas-s.onnx')

error:
[2023-05-31 15:03:01] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-05-31 15:03:03] WARNING - redirects.py - NOTE: Redirects are currently not supported in Windows or MacOs.
[2023-05-31 15:03:05] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-05-31 15:03:05] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-05-31 15:03:05] WARNING - export.py - Failed to import pytorch_quantization
[2023-05-31 15:03:05] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-05-31 15:03:05] WARNING - env_sanity_check.py - Failed to verify operating system: Deci officially supports only Linux kernels. Some features may not work as expected.
[2023-05-31 15:03:05] INFO - checkpoint_utils.py - Successfully loaded model weights from yolo_nas_s_coco.pth checkpoint.
[2023-05-31 15:03:05] WARNING - conversion.py - input_shape is deprecated and will be removed in the next major release.Use the convert_to_onnx(..., prep_model_for_conversion_kwargs(input_size=(1, 3, 640, 640))) instead
C:\Users\lllstandout\AppData\Roaming\Python\Python39\site-packages\torch\onnx\symbolic_opset9.py:714: UserWarning: This model contains a squeeze operation on dimension 1. If the model is intended to be used with dynamic input shapes, please use opset version 11 to export the model.
  warnings.warn("This model contains a squeeze operation on dimension " + str(squeeze_dim) + ". If the model is " +
Traceback (most recent call last):
  File "G:\Item_done\yolo\yolo-nas\super-gradients-master\yolo_nas_export.py", line 19, in <module>
    models.convert_to_onnx(model=net, input_shape=(3, 640, 640), out_path='yolo-nas-s.onnx')
  File "G:\Item_done\yolo\yolo-nas\super-gradients-master\src\super_gradients\common\decorators\factory_decorator.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "G:\Item_done\yolo\yolo-nas\super-gradients-master\src\super_gradients\common\decorators\factory_decorator.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "G:\Item_done\yolo\yolo-nas\super-gradients-master\src\super_gradients\training\models\conversion.py", line 215, in convert_to_onnx
    onnx_simplify(out_path, out_path)
  File "G:\Item_done\yolo\yolo-nas\super-gradients-master\src\super_gradients\training\models\conversion.py", line 273, in onnx_simplify
    model_sim, check = simplify(model=onnx_path)
  File "C:\Users\lllstandout\.conda\envs\yolov8\lib\site-packages\onnxsim\onnx_simplifier.py", line 199, in simplify
    model_opt_bytes = C.simplify(
  File "C:\Users\lllstandout\.conda\envs\yolov8\lib\site-packages\onnxsim\onnx_simplifier.py", line 260, in Run
    output_arrs = sess.run(output_names, inputs, run_options=run_options)
  File "C:\Users\lllstandout\.conda\envs\yolov8\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: onnx::Concat_851 Got: 3 Expected: 2 Please fix either the inputs or the model.

Process finished with exit code 1

**Comment by rose-jinyang** [comment] 2023-06-01 03:35
Hello
How are you?
I trained a custom object detection model with YOLO-NAS architecture.
The trained PyTorch model works well.
I am going to do inference with ONNX model rather than PyTorch model.
So I am trying to use this project.
I successfully exported an onnx model by the following script.

from super_gradients.training import models
net = models.get('yolo_nas_l', num_classes=2, checkpoint_path='ckpts/yolo_nas_l/ckpt_best.pth')
models.convert_to_onnx(model=net, input_shape=(3, 640, 640), out_path='yolo_nas_l.onnx')

I tried to use ONNX runtime backend inference in your project.
But the scores of all the detected objects are very low.
What do you think about this issue?

**Comment by Uaena-Wang** [comment] 2023-06-01 03:42
> Hello How are you? I trained a custom object detection model with YOLO-NAS architecture. The trained PyTorch model works well. I am going to do inference with ONNX model rather than PyTorch model. So I am trying to use this project. I successfully exported an onnx model by the following script.
> 
> from super_gradients.training import models net = models.get('yolo_nas_l', num_classes=2, checkpoint_path='ckpts/yolo_nas_l/ckpt_best.pth') models.convert_to_onnx(model=net, input_shape=(3, 640, 640), out_path='yolo_nas_l.onnx')
> 
> I tried to use ONNX runtime backend inference in your project. But the scores of all the detected objects are very low. What do you think about this issue?

Me too!!!  According to my understanding, I think there is a problem when the custom training model .pth is converted to onnx, because the pre-trained coco weight conversion of onnx will not have this problem. I can convert the weight of coco to onnx and run the entire project correctly. But my own custom dataset onnx doesn't work，even thought I can run .pth and get right results.

**Comment by Hyuto** [comment] 2023-06-01 16:56
Hello guys, I've check the code isn't work well with custom trained model. I'm trying to fix a few things to begin with, but this is labelled bug at the main repo super-gradient have https://github.com/Deci-AI/super-gradients/issues/1108 as @Uaena-Wang have open issue there. You can keep up about this issue there because I can't do a thing if there is a bug at conversion model to onnx. Currently I'm trying to implement preprocess and postprocess from the main repo since there is a difference how to handle image and boxes.

**Comment by Hyuto** [comment] 2023-06-02 19:30
Hello guys, just a little update here. I think I found where the problem is. Based on pretrained model from @Uaena-Wang I have found the problem is the preprocessing steps. Preprocessing steps from YOLO-NAS original model and the custom model is different so it affect the detection result.

![image](https://github.com/Hyuto/yolo-nas-onnx/assets/64422277/553a8327-b848-414f-8735-9754b9cf4ceb)

as you can see from the image above the preprocessing steps is different. If you see the source from https://github.com/Deci-AI/super-gradients/blob/1c67ce369b53daf162a91faacb24f3501e7b84ad/src/super_gradients/training/processing/processing.py#L262 the custom model preprocessing steps is using yolox_coco not yolo_nas.

when the preprocessing steps is the same then the result is the same as torch model

![image](https://github.com/Hyuto/yolo-nas-onnx/assets/64422277/157686bd-2f23-483c-8594-60cc3d52b816)

**Comment by Uaena-Wang** [comment] 2023-06-03 00:53
Hi, Hyuto！Really appreciate you taking the time to find the source of the problem and find a solution, but I don't know how to modify the preprocessing in the onnx code, can you update your code? Thank you again!

**Comment by Uaena-Wang** [comment] 2023-06-03 00:54
> Hello guys, just a little update here. I think I found where the problem is. Based on pretrained model from @Uaena-Wang I have found the problem is the preprocessing steps. Preprocessing steps from YOLO-NAS original model and the custom model is different so it affect the detection result.
> 
> ![image](https://user-images.githubusercontent.com/64422277/242971603-553a8327-b848-414f-8735-9754b9cf4ceb.png)
> 
> as you can see from the image above the preprocessing steps is different. If you see the source from https://github.com/Deci-AI/super-gradients/blob/1c67ce369b53daf162a91faacb24f3501e7b84ad/src/super_gradients/training/processing/processing.py#L262 the custom model preprocessing steps is using yolox_coco not yolo_nas.
> 
> when the preprocessing steps is the same then the result is the same as torch model
> 
> ![image](https://user-images.githubusercontent.com/64422277/242975036-157686bd-2f23-483c-8594-60cc3d52b816.png)

Hi, Hyuto. Really appreciate you taking the time to find the source of the problem and find a solution, but I don't know how to modify the preprocessing in the onnx code, can you update your code? Thank you again!

**Comment by Hyuto** [comment] 2023-06-03 03:50
I'm sorry, for now I think change my code base isn't really a good way to go. Because the preprocessing step the model you use isn't the standard YOLO-NAS preprocessing step. If I change it the original model inferencing will got the trouble. 

For now can you tell me how you train your custom trained model. Maybe from there I can debug why your model isn't using YOLO-NAS preprocessing steps.

**Comment by Uaena-Wang** [comment] 2023-06-03 04:07
> I'm sorry, for now I think change my code base isn't really a good way to go. Because the preprocessing step the model you use isn't the standard YOLO-NAS preprocessing step. If I change it the original model inferencing will got the trouble.
> 
> For now can you tell me how you train your custom trained model. Maybe from there I can debug why your model isn't using YOLO-NAS preprocessing steps.

Thank you, I understand, I followed this [repo]( https://github.com/naseemap47/YOLO-NAS) to train a custom model, if possible, can you send me the correct code you debugged on my onnx file, I will try it!
you can reach me on marquitaschramekzmx27@gmail.com, thanks again.

**Comment by Hyuto** [comment] 2023-06-04 07:25
Hello, just a little update here. I'm planning to make config (metadata file) for custom trained model. However it'll take a time to implement I expect to be done in Monday or Tuesday (GMT+7). Sorry for make you all wait, but I think this will be better implementation for YOLO-NAS onnx model.

**Comment by xinsuinizhuan** [comment] 2023-06-07 03:35
could you help me?
i use the follow code export the .pth to onnx，but get the error:

from super_gradients.training import models
net = models.get('yolo_nas_l', num_classes=80, checkpoint_path='yolo_nas_l_coco.pth')
models.convert_to_onnx(model=net, input_shape=(3, 640, 640), out_path='yolo_nas_l.onnx')

  File "xxx\site-packages\onnxsim\onnx_simplifier.py", line 260, in Run
    output_arrs = sess.run(output_names, inputs, run_options=run_options)
  File "xxx\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: onnx::Concat_980 Got: 3 Expected: 2 Please fix either the inputs or the model.

**Comment by Uaena-Wang** [comment] 2023-06-07 04:29
> could you help me? i use the follow code export the .pth to onnx，but get the error, the yolo_nas_l_coco.pth is the pretrained model:
> 
> from super_gradients.training import models net = models.get('yolo_nas_l', num_classes=80, checkpoint_path='yolo_nas_l_coco.pth') models.convert_to_onnx(model=net, input_shape=(3, 640, 640), out_path='yolo_nas_l.onnx')
> 
> File "xxx\site-packages\onnxsim\onnx_simplifier.py", line 260, in Run output_arrs = sess.run(output_names, inputs, run_options=run_options) File "xxx\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run return self._sess.run(output_names, input_feed, run_options) onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: onnx::Concat_980 Got: 3 Expected: 2 Please fix either the inputs or the model.

Based on my experience，even if this error is reported, the onnx file can still be exported, and onnx is available.

**Comment by xinsuinizhuan** [comment] 2023-06-07 05:50
yes, it exported. Let me have a try, whether it works.

**Comment by xinsuinizhuan** [comment] 2023-06-07 06:08
I get the onnx file，but when i convert the onnx file to trt, still break:
xxx\bin>trtexec --fp16 --int8 --avgRuns=100 --onnx=model.onnx
&&&& RUNNING TensorRT.trtexec [TensorRT v8204] # trtexec --fp16 --int8 --avgRuns=100 --onnx=model.onnx
[06/07/2023-14:00:56] [I] === Model Options ===
[06/07/2023-14:00:56] [I] Format: ONNX
[06/07/2023-14:00:56] [I] Model: model.onnx
[06/07/2023-14:00:56] [I] Output:
[06/07/2023-14:00:56] [I] === Build Options ===
[06/07/2023-14:00:56] [I] Max batch: explicit batch
[06/07/2023-14:00:56] [I] Workspace: 16 MiB
[06/07/2023-14:00:56] [I] minTiming: 1
[06/07/2023-14:00:56] [I] avgTiming: 8
[06/07/2023-14:00:56] [I] Precision: FP32+FP16+INT8
[06/07/2023-14:00:56] [I] Calibration: Dynamic
[06/07/2023-14:00:56] [I] Refit: Disabled
[06/07/2023-14:00:56] [I] Sparsity: Disabled
[06/07/2023-14:00:56] [I] Safe mode: Disabled
[06/07/2023-14:00:56] [I] DirectIO mode: Disabled
[06/07/2023-14:00:56] [I] Restricted mode: Disabled
[06/07/2023-14:00:56] [I] Save engine:
[06/07/2023-14:00:56] [I] Load engine:
[06/07/2023-14:00:56] [I] Profiling verbosity: 0
[06/07/2023-14:00:56] [I] Tactic sources: Using default tactic sources
[06/07/2023-14:00:56] [I] timingCacheMode: local
[06/07/2023-14:00:56] [I] timingCacheFile:
[06/07/2023-14:00:56] [I] Input(s)s format: fp32:CHW
[06/07/2023-14:00:56] [I] Output(s)s format: fp32:CHW
[06/07/2023-14:00:56] [I] Input build shapes: model
[06/07/2023-14:00:56] [I] Input calibration shapes: model
[06/07/2023-14:00:56] [I] === System Options ===
[06/07/2023-14:00:56] [I] Device: 0
[06/07/2023-14:00:56] [I] DLACore:
[06/07/2023-14:00:56] [I] Plugins:
[06/07/2023-14:00:56] [I] === Inference Options ===
[06/07/2023-14:00:56] [I] Batch: Explicit
[06/07/2023-14:00:56] [I] Input inference shapes: model
[06/07/2023-14:00:56] [I] Iterations: 10
[06/07/2023-14:00:56] [I] Duration: 3s (+ 200ms warm up)
[06/07/2023-14:00:56] [I] Sleep time: 0ms
[06/07/2023-14:00:56] [I] Idle time: 0ms
[06/07/2023-14:00:56] [I] Streams: 1
[06/07/2023-14:00:56] [I] ExposeDMA: Disabled
[06/07/2023-14:00:56] [I] Data transfers: Enabled
[06/07/2023-14:00:56] [I] Spin-wait: Disabled
[06/07/2023-14:00:56] [I] Multithreading: Disabled
[06/07/2023-14:00:56] [I] CUDA Graph: Disabled
[06/07/2023-14:00:56] [I] Separate profiling: Disabled
[06/07/2023-14:00:56] [I] Time Deserialize: Disabled
[06/07/2023-14:00:56] [I] Time Refit: Disabled
[06/07/2023-14:00:56] [I] Skip inference: Disabled
[06/07/2023-14:00:56] [I] Inputs:
[06/07/2023-14:00:56] [I] === Reporting Options ===
[06/07/2023-14:00:56] [I] Verbose: Disabled
[06/07/2023-14:00:56] [I] Averages: 100 inferences
[06/07/2023-14:00:56] [I] Percentile: 99
[06/07/2023-14:00:56] [I] Dump refittable layers:Disabled
[06/07/2023-14:00:56] [I] Dump output: Disabled
[06/07/2023-14:00:56] [I] Profile: Disabled
[06/07/2023-14:00:56] [I] Export timing to JSON file:
[06/07/2023-14:00:56] [I] Export output to JSON file:
[06/07/2023-14:00:56] [I] Export profile to JSON file:
[06/07/2023-14:00:56] [I]
[06/07/2023-14:00:57] [I] === Device Information ===
[06/07/2023-14:00:57] [I] Selected Device: NVIDIA GeForce RTX 3060 Laptop GPU
[06/07/2023-14:00:57] [I] Compute Capability: 8.6
[06/07/2023-14:00:57] [I] SMs: 30
[06/07/2023-14:00:57] [I] Compute Clock Rate: 1.702 GHz
[06/07/2023-14:00:57] [I] Device Global Memory: 6143 MiB
[06/07/2023-14:00:57] [I] Shared Memory per SM: 100 KiB
[06/07/2023-14:00:57] [I] Memory Bus Width: 192 bits (ECC disabled)
[06/07/2023-14:00:57] [I] Memory Clock Rate: 7.001 GHz
[06/07/2023-14:00:57] [I]
[06/07/2023-14:00:57] [I] TensorRT version: 8.2.4
[06/07/2023-14:00:58] [I] [TRT] [MemUsageChange] Init CUDA: CPU +653, GPU +0, now: CPU 19562, GPU 1210 (MiB)
[06/07/2023-14:00:59] [I] [TRT] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 19619 MiB, GPU 1210 MiB
[06/07/2023-14:00:59] [I] [TRT] [MemUsageSnapshot] End constructing builder kernel library: CPU 19827 MiB, GPU 1254 MiB
[06/07/2023-14:00:59] [I] Start parsing network model
[06/07/2023-14:00:59] [I] [TRT] ----------------------------------------------------------------
[06/07/2023-14:00:59] [I] [TRT] Input filename:   model.onnx
[06/07/2023-14:00:59] [I] [TRT] ONNX IR version:  0.0.4
[06/07/2023-14:00:59] [I] [TRT] Opset version:    9
[06/07/2023-14:00:59] [I] [TRT] Producer name:    pytorch
[06/07/2023-14:00:59] [I] [TRT] Producer version: 1.11.0
[06/07/2023-14:00:59] [I] [TRT] Domain:
[06/07/2023-14:00:59] [I] [TRT] Model version:    0
[06/07/2023-14:00:59] [I] [TRT] Doc string:
[06/07/2023-14:00:59] [I] [TRT] ----------------------------------------------------------------
[06/07/2023-14:00:59] [W] [TRT] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[06/07/2023-14:00:59] [I] [TRT] No importer registered for op: NonZero. Attempting to import as plugin.
[06/07/2023-14:00:59] [I] [TRT] Searching for plugin: NonZero, plugin_version: 1, plugin_namespace:
[06/07/2023-14:00:59] [E] [TRT] ModelImporter.cpp:773: While parsing node number 274 [NonZero -> "onnx::Transpose_819"]:
[06/07/2023-14:00:59] [E] [TRT] ModelImporter.cpp:774: --- Begin node ---
[06/07/2023-14:00:59] [E] [TRT] ModelImporter.cpp:775: input: "onnx::NonZero_818"
output: "onnx::Transpose_819"
name: "NonZero_274"
op_type: "NonZero"

[06/07/2023-14:00:59] [E] [TRT] ModelImporter.cpp:776: --- End node ---
[06/07/2023-14:00:59] [E] [TRT] ModelImporter.cpp:779: ERROR: builtin_op_importers.cpp:4870 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[06/07/2023-14:00:59] [E] Failed to parse onnx file
[06/07/2023-14:00:59] [I] Finish parsing network model
[06/07/2023-14:00:59] [E] Parsing model failed
[06/07/2023-14:00:59] [E] Failed to create engine from model.
[06/07/2023-14:00:59] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8204] # trtexec --fp16 --int8 --avgRuns=100 --onnx=model.onnx

**Comment by xinsuinizhuan** [comment] 2023-06-07 06:09
do you only forward with the onnxruntime? No try tensorrt forward?

**Comment by Uaena-Wang** [comment] 2023-06-07 07:07
> do you only forward with the onnxruntime? No try tensorrt forward?

yes，because I only need to deploy to the cpu, I didn't try trt.

**Comment by Hyuto** [comment] 2023-06-08 16:20
Hello Guys,

It's been a few days from this issue was opened. I'm glad to inform you the problem is fixed. For custom model trainer you can take a look on this https://github.com/Hyuto/yolo-nas-onnx/tree/master/yolo-nas-py#custom-model. Those steps is basically tell you what to do to run your custom trained YOLO-NAS model. However I just test it myself so maybe there's a bug I miss. I look forward to hear your feedback for that. 

Thank you

**Comment by Hyuto** [comment] 2023-06-27 08:08
Since there is no problem left I assume it work well with custom trained YOLO-NAS model. 

I'm closing this issue, feel free to open it if there is any bug on inferencing custom trained YOLO-NAS model.

**Closed by Hyuto** 2023-06-27 08:08 UTC
